### PR TITLE
move declaration of id2type_impl in 2-arg msvc_extract_type before co…

### PR DESCRIPTION
**Pull request by mathcounts4**
…mplete id2type_impl specialization

### CODE REVIEW

**Comment by mathcounts4** [comment]
This fixes https://github.com/boostorg/scope_exit/issues/9 but github won't let me attach it to this pull request

**Comment by MarcelRaad** [comment]
Wasn't that fixed by https://github.com/boostorg/scope_exit/pull/3? That code shouldn't be active at all with Visual Studio 2017+.

**Comment by mathcounts4** [comment]
> Wasn't that fixed by #3? That code shouldn't be active at all with Visual Studio 2017+.

True. I saw this issue with boost 1.65.1 in VS2017 but no longer with boost 1.70 and VS2019.

Would this change still be useful for VS2015-?

**Comment by mathcounts4** [comment]
Fixed by https://github.com/boostorg/scope_exit/pull/3 - closing this pull request

**Pull request closed without merging**
